### ISSUE TITLE
Docker image size for AMD64

### ISSUE THREAD

**Issue by ngosang** [jellyfin/jellyfin-metapackages#36]
I have been using the LinuxServer Docker image for several years and recently I moved to the official Docker image.
I noticed there is a significant size difference between both images for AMD64. I don't care if the image is big if all dependencies/packages are required. The thing is, or you are including more packages than required or they are missing something important (bug).

https://hub.docker.com/r/jellyfin/jellyfin
![image](https://github.com/jellyfin/jellyfin-metapackages/assets/10577978/30c872a7-9d8b-4ee6-978c-34fcdc28a769)

https://hub.docker.com/r/linuxserver/jellyfin
![image](https://github.com/jellyfin/jellyfin-metapackages/assets/10577978/ecb3467a-dcc7-4c99-aecd-0821adfbe35c)

His Dockerfiles are here => https://github.com/linuxserver/docker-jellyfin

**Comment by nyanmisaka** [comment]
The diff part is basically Intel [compute-runtime](https://github.com/intel/compute-runtime/releases) for easy of use.

On LSIO image it just delays the download. https://mods.linuxserver.io/?mod=jellyfin

**Comment by ngosang** [comment]
Thanks
